name: lws-poc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      working-directory: ./servers-api
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: ./servers-api
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      working-directory: ./servers-api
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./servers-api
      run: chmod -R 777 storage bootstrap/cache
    - name: Create import folder
      working-directory: ./servers-api
      run: mkdir storage/app/import
    - name: Copy csv file with the source data
      run: cp etc/import/servers_filters_assignment.csv servers-api/storage/app/import/
    - name: Run artisan command to import data
      working-directory: ./servers-api
      run: php artisan servers:import
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      working-directory: ./servers-api
      run: vendor/bin/phpunit
